name: Build & Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python & install MLflow
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install MLflow CLI
        run: pip install mlflow==2.22.0

      - name: Download model artifact from DagsHub
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/Marw1BS/dvc.mlflow
        run: |
          mkdir -p models/random_forest_model
          mlflow artifacts download \
            --run-id 920f98cd99cc46909114a50fa7b360f4 \
            --artifact-path model.joblib \
            --dst-path models/random_forest_model

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t mrwnbnslm/dv2:latest .

      - name: Push to DockerHub
        run: docker push mrwnbnslm/dv2:latest
